/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderpadsRouteImport } from './routes/underpads'
import { Route as DiapersRouteImport } from './routes/diapers'
import { Route as IndexRouteImport } from './routes/index'

const UnderpadsRoute = UnderpadsRouteImport.update({
  id: '/underpads',
  path: '/underpads',
  getParentRoute: () => rootRouteImport,
} as any)
const DiapersRoute = DiapersRouteImport.update({
  id: '/diapers',
  path: '/diapers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diapers': typeof DiapersRoute
  '/underpads': typeof UnderpadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diapers': typeof DiapersRoute
  '/underpads': typeof UnderpadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diapers': typeof DiapersRoute
  '/underpads': typeof UnderpadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diapers' | '/underpads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diapers' | '/underpads'
  id: '__root__' | '/' | '/diapers' | '/underpads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiapersRoute: typeof DiapersRoute
  UnderpadsRoute: typeof UnderpadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/underpads': {
      id: '/underpads'
      path: '/underpads'
      fullPath: '/underpads'
      preLoaderRoute: typeof UnderpadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diapers': {
      id: '/diapers'
      path: '/diapers'
      fullPath: '/diapers'
      preLoaderRoute: typeof DiapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiapersRoute: DiapersRoute,
  UnderpadsRoute: UnderpadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
