/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhereToBuyRouteImport } from './routes/where-to-buy'
import { Route as UnderpadsRouteImport } from './routes/underpads'
import { Route as DiapersRouteImport } from './routes/diapers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUnderpadsRouteImport } from './routes/admin.underpads'
import { Route as AdminDiapersRouteImport } from './routes/admin.diapers'

const WhereToBuyRoute = WhereToBuyRouteImport.update({
  id: '/where-to-buy',
  path: '/where-to-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderpadsRoute = UnderpadsRouteImport.update({
  id: '/underpads',
  path: '/underpads',
  getParentRoute: () => rootRouteImport,
} as any)
const DiapersRoute = DiapersRouteImport.update({
  id: '/diapers',
  path: '/diapers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnderpadsRoute = AdminUnderpadsRouteImport.update({
  id: '/underpads',
  path: '/underpads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiapersRoute = AdminDiapersRouteImport.update({
  id: '/diapers',
  path: '/diapers',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/diapers': typeof DiapersRoute
  '/underpads': typeof UnderpadsRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/admin/diapers': typeof AdminDiapersRoute
  '/admin/underpads': typeof AdminUnderpadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/diapers': typeof DiapersRoute
  '/underpads': typeof UnderpadsRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/admin/diapers': typeof AdminDiapersRoute
  '/admin/underpads': typeof AdminUnderpadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/diapers': typeof DiapersRoute
  '/underpads': typeof UnderpadsRoute
  '/where-to-buy': typeof WhereToBuyRoute
  '/admin/diapers': typeof AdminDiapersRoute
  '/admin/underpads': typeof AdminUnderpadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/diapers'
    | '/underpads'
    | '/where-to-buy'
    | '/admin/diapers'
    | '/admin/underpads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/diapers'
    | '/underpads'
    | '/where-to-buy'
    | '/admin/diapers'
    | '/admin/underpads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/diapers'
    | '/underpads'
    | '/where-to-buy'
    | '/admin/diapers'
    | '/admin/underpads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DiapersRoute: typeof DiapersRoute
  UnderpadsRoute: typeof UnderpadsRoute
  WhereToBuyRoute: typeof WhereToBuyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/where-to-buy': {
      id: '/where-to-buy'
      path: '/where-to-buy'
      fullPath: '/where-to-buy'
      preLoaderRoute: typeof WhereToBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/underpads': {
      id: '/underpads'
      path: '/underpads'
      fullPath: '/underpads'
      preLoaderRoute: typeof UnderpadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diapers': {
      id: '/diapers'
      path: '/diapers'
      fullPath: '/diapers'
      preLoaderRoute: typeof DiapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/underpads': {
      id: '/admin/underpads'
      path: '/underpads'
      fullPath: '/admin/underpads'
      preLoaderRoute: typeof AdminUnderpadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diapers': {
      id: '/admin/diapers'
      path: '/diapers'
      fullPath: '/admin/diapers'
      preLoaderRoute: typeof AdminDiapersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDiapersRoute: typeof AdminDiapersRoute
  AdminUnderpadsRoute: typeof AdminUnderpadsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDiapersRoute: AdminDiapersRoute,
  AdminUnderpadsRoute: AdminUnderpadsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DiapersRoute: DiapersRoute,
  UnderpadsRoute: UnderpadsRoute,
  WhereToBuyRoute: WhereToBuyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
