/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhereToBuyRouteImport } from './routes/where-to-buy'
import { Route as UnderpadsRouteImport } from './routes/underpads'
import { Route as DiapersRouteImport } from './routes/diapers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnderpadsIndexRouteImport } from './routes/underpads.index'
import { Route as DiapersIndexRouteImport } from './routes/diapers.index'
import { Route as UnderpadsSizeRouteImport } from './routes/underpads.$size'
import { Route as TipsSkinCareRouteImport } from './routes/tips.skin-care'
import { Route as TipsSizeGuideRouteImport } from './routes/tips.size-guide'
import { Route as TipsAbsorptionTableRouteImport } from './routes/tips.absorption-table'
import { Route as DiapersSizeRouteImport } from './routes/diapers.$size'
import { Route as AdminUnderpadsRouteImport } from './routes/admin.underpads'
import { Route as AdminDiapersRouteImport } from './routes/admin.diapers'

const WhereToBuyRoute = WhereToBuyRouteImport.update({
  id: '/where-to-buy',
  path: '/where-to-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderpadsRoute = UnderpadsRouteImport.update({
  id: '/underpads',
  path: '/underpads',
  getParentRoute: () => rootRouteImport,
} as any)
const DiapersRoute = DiapersRouteImport.update({
  id: '/diapers',
  path: '/diapers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderpadsIndexRoute = UnderpadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnderpadsRoute,
} as any)
const DiapersIndexRoute = DiapersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiapersRoute,
} as any)
const UnderpadsSizeRoute = UnderpadsSizeRouteImport.update({
  id: '/$size',
  path: '/$size',
  getParentRoute: () => UnderpadsRoute,
} as any)
const TipsSkinCareRoute = TipsSkinCareRouteImport.update({
  id: '/tips/skin-care',
  path: '/tips/skin-care',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsSizeGuideRoute = TipsSizeGuideRouteImport.update({
  id: '/tips/size-guide',
  path: '/tips/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsAbsorptionTableRoute = TipsAbsorptionTableRouteImport.update({
  id: '/tips/absorption-table',
  path: '/tips/absorption-table',
  getParentRoute: () => rootRouteImport,
} as any)
const DiapersSizeRoute = DiapersSizeRouteImport.update({
  id: '/$size',
  path: '/$size',
  getParentRoute: () => DiapersRoute,
} as any)
const AdminUnderpadsRoute = AdminUnderpadsRouteImport.update({
  id: '/underpads',
  path: '/underpads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiapersRoute = AdminDiapersRouteImport.update({
  id: '/diapers',
  path: '/diapers',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/diapers': typeof DiapersRouteWithChildren
  '/underpads': typeof UnderpadsRouteWithChildren
  '/where-to-buy': typeof WhereToBuyRoute
  '/admin/diapers': typeof AdminDiapersRoute
  '/admin/underpads': typeof AdminUnderpadsRoute
  '/diapers/$size': typeof DiapersSizeRoute
  '/tips/absorption-table': typeof TipsAbsorptionTableRoute
  '/tips/size-guide': typeof TipsSizeGuideRoute
  '/tips/skin-care': typeof TipsSkinCareRoute
  '/underpads/$size': typeof UnderpadsSizeRoute
  '/diapers/': typeof DiapersIndexRoute
  '/underpads/': typeof UnderpadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/where-to-buy': typeof WhereToBuyRoute
  '/admin/diapers': typeof AdminDiapersRoute
  '/admin/underpads': typeof AdminUnderpadsRoute
  '/diapers/$size': typeof DiapersSizeRoute
  '/tips/absorption-table': typeof TipsAbsorptionTableRoute
  '/tips/size-guide': typeof TipsSizeGuideRoute
  '/tips/skin-care': typeof TipsSkinCareRoute
  '/underpads/$size': typeof UnderpadsSizeRoute
  '/diapers': typeof DiapersIndexRoute
  '/underpads': typeof UnderpadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/diapers': typeof DiapersRouteWithChildren
  '/underpads': typeof UnderpadsRouteWithChildren
  '/where-to-buy': typeof WhereToBuyRoute
  '/admin/diapers': typeof AdminDiapersRoute
  '/admin/underpads': typeof AdminUnderpadsRoute
  '/diapers/$size': typeof DiapersSizeRoute
  '/tips/absorption-table': typeof TipsAbsorptionTableRoute
  '/tips/size-guide': typeof TipsSizeGuideRoute
  '/tips/skin-care': typeof TipsSkinCareRoute
  '/underpads/$size': typeof UnderpadsSizeRoute
  '/diapers/': typeof DiapersIndexRoute
  '/underpads/': typeof UnderpadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/diapers'
    | '/underpads'
    | '/where-to-buy'
    | '/admin/diapers'
    | '/admin/underpads'
    | '/diapers/$size'
    | '/tips/absorption-table'
    | '/tips/size-guide'
    | '/tips/skin-care'
    | '/underpads/$size'
    | '/diapers/'
    | '/underpads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/where-to-buy'
    | '/admin/diapers'
    | '/admin/underpads'
    | '/diapers/$size'
    | '/tips/absorption-table'
    | '/tips/size-guide'
    | '/tips/skin-care'
    | '/underpads/$size'
    | '/diapers'
    | '/underpads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/diapers'
    | '/underpads'
    | '/where-to-buy'
    | '/admin/diapers'
    | '/admin/underpads'
    | '/diapers/$size'
    | '/tips/absorption-table'
    | '/tips/size-guide'
    | '/tips/skin-care'
    | '/underpads/$size'
    | '/diapers/'
    | '/underpads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DiapersRoute: typeof DiapersRouteWithChildren
  UnderpadsRoute: typeof UnderpadsRouteWithChildren
  WhereToBuyRoute: typeof WhereToBuyRoute
  TipsAbsorptionTableRoute: typeof TipsAbsorptionTableRoute
  TipsSizeGuideRoute: typeof TipsSizeGuideRoute
  TipsSkinCareRoute: typeof TipsSkinCareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/where-to-buy': {
      id: '/where-to-buy'
      path: '/where-to-buy'
      fullPath: '/where-to-buy'
      preLoaderRoute: typeof WhereToBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/underpads': {
      id: '/underpads'
      path: '/underpads'
      fullPath: '/underpads'
      preLoaderRoute: typeof UnderpadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diapers': {
      id: '/diapers'
      path: '/diapers'
      fullPath: '/diapers'
      preLoaderRoute: typeof DiapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/underpads/': {
      id: '/underpads/'
      path: '/'
      fullPath: '/underpads/'
      preLoaderRoute: typeof UnderpadsIndexRouteImport
      parentRoute: typeof UnderpadsRoute
    }
    '/diapers/': {
      id: '/diapers/'
      path: '/'
      fullPath: '/diapers/'
      preLoaderRoute: typeof DiapersIndexRouteImport
      parentRoute: typeof DiapersRoute
    }
    '/underpads/$size': {
      id: '/underpads/$size'
      path: '/$size'
      fullPath: '/underpads/$size'
      preLoaderRoute: typeof UnderpadsSizeRouteImport
      parentRoute: typeof UnderpadsRoute
    }
    '/tips/skin-care': {
      id: '/tips/skin-care'
      path: '/tips/skin-care'
      fullPath: '/tips/skin-care'
      preLoaderRoute: typeof TipsSkinCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips/size-guide': {
      id: '/tips/size-guide'
      path: '/tips/size-guide'
      fullPath: '/tips/size-guide'
      preLoaderRoute: typeof TipsSizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips/absorption-table': {
      id: '/tips/absorption-table'
      path: '/tips/absorption-table'
      fullPath: '/tips/absorption-table'
      preLoaderRoute: typeof TipsAbsorptionTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diapers/$size': {
      id: '/diapers/$size'
      path: '/$size'
      fullPath: '/diapers/$size'
      preLoaderRoute: typeof DiapersSizeRouteImport
      parentRoute: typeof DiapersRoute
    }
    '/admin/underpads': {
      id: '/admin/underpads'
      path: '/underpads'
      fullPath: '/admin/underpads'
      preLoaderRoute: typeof AdminUnderpadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diapers': {
      id: '/admin/diapers'
      path: '/diapers'
      fullPath: '/admin/diapers'
      preLoaderRoute: typeof AdminDiapersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDiapersRoute: typeof AdminDiapersRoute
  AdminUnderpadsRoute: typeof AdminUnderpadsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDiapersRoute: AdminDiapersRoute,
  AdminUnderpadsRoute: AdminUnderpadsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DiapersRouteChildren {
  DiapersSizeRoute: typeof DiapersSizeRoute
  DiapersIndexRoute: typeof DiapersIndexRoute
}

const DiapersRouteChildren: DiapersRouteChildren = {
  DiapersSizeRoute: DiapersSizeRoute,
  DiapersIndexRoute: DiapersIndexRoute,
}

const DiapersRouteWithChildren =
  DiapersRoute._addFileChildren(DiapersRouteChildren)

interface UnderpadsRouteChildren {
  UnderpadsSizeRoute: typeof UnderpadsSizeRoute
  UnderpadsIndexRoute: typeof UnderpadsIndexRoute
}

const UnderpadsRouteChildren: UnderpadsRouteChildren = {
  UnderpadsSizeRoute: UnderpadsSizeRoute,
  UnderpadsIndexRoute: UnderpadsIndexRoute,
}

const UnderpadsRouteWithChildren = UnderpadsRoute._addFileChildren(
  UnderpadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DiapersRoute: DiapersRouteWithChildren,
  UnderpadsRoute: UnderpadsRouteWithChildren,
  WhereToBuyRoute: WhereToBuyRoute,
  TipsAbsorptionTableRoute: TipsAbsorptionTableRoute,
  TipsSizeGuideRoute: TipsSizeGuideRoute,
  TipsSkinCareRoute: TipsSkinCareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
